// <auto-generated />
using System;
using Infrastructure.FGIS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.FGIS.Database.Maintenance.Migrations
{
    [DbContext(typeof(FGISDatabase))]
    [Migration("20250628105309_MergeEtalon")]
    partial class MergeEtalon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.FGIS.Database.Entities.Etalon", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<bool>("Applicability")
                        .HasColumnType("boolean")
                        .HasColumnName("applicability");

                    b.Property<string>("Factory_Num")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("factory_num");

                    b.Property<string>("MiNotation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mi_notation");

                    b.Property<string>("MiType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mi_type");

                    b.Property<string>("MiType_Num")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mi_type_num");

                    b.Property<string>("Modification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modification");

                    b.Property<string>("NpEnumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("np_enumber");

                    b.Property<string>("RankClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rank_class");

                    b.Property<string>("RankCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rank_code");

                    b.Property<string>("Schematitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schematitle");

                    b.Property<string>("Schematype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schematype");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Number")
                        .HasName("pk_etalons");

                    b.ToTable("etalons", (string)null);
                });

            modelBuilder.Entity("Infrastructure.FGIS.Database.Entities.EtalonsId", b =>
                {
                    b.Property<string>("Rmieta_id")
                        .HasColumnType("text")
                        .HasColumnName("rmieta_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reg_number");

                    b.HasKey("Rmieta_id")
                        .HasName("pk_etalon_ids");

                    b.ToTable("etalon_ids", (string)null);
                });

            modelBuilder.Entity("Infrastructure.FGIS.Database.Entities.MonthResult", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<bool>("EtalonsCollected")
                        .HasColumnType("boolean")
                        .HasColumnName("etalons_collected");

                    b.Property<bool>("EtalonsIdsCollected")
                        .HasColumnType("boolean")
                        .HasColumnName("etalons_ids_collected");

                    b.Property<bool>("VerificationIdsCollected")
                        .HasColumnType("boolean")
                        .HasColumnName("verification_ids_collected");

                    b.Property<bool>("VerificationsCollected")
                        .HasColumnType("boolean")
                        .HasColumnName("verifications_collected");

                    b.HasKey("Date")
                        .HasName("pk_month_results");

                    b.ToTable("month_results", (string)null);
                });

            modelBuilder.Entity("Infrastructure.FGIS.Database.Entities.Verification", b =>
                {
                    b.Property<string>("Vri_id")
                        .HasColumnType("text")
                        .HasColumnName("vri_id");

                    b.HasKey("Vri_id")
                        .HasName("pk_verifications");

                    b.ToTable("verifications", (string)null);
                });

            modelBuilder.Entity("Infrastructure.FGIS.Database.Entities.VerificationId", b =>
                {
                    b.Property<string>("Vri_id")
                        .HasColumnType("text")
                        .HasColumnName("vri_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("Vri_id")
                        .HasName("pk_verification_ids");

                    b.ToTable("verification_ids", (string)null);
                });

            modelBuilder.Entity("Infrastructure.FGIS.Database.Entities.Etalon", b =>
                {
                    b.OwnsMany("Infrastructure.FGIS.Database.Entities.Etalon+EtalonVerificationDocs", "CResults", b1 =>
                        {
                            b1.Property<string>("EtalonNumber")
                                .HasColumnType("text")
                                .HasColumnName("etalon_number");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("Applicability")
                                .HasColumnType("boolean")
                                .HasColumnName("applicability");

                            b1.Property<string>("Org_Title")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("org_title");

                            b1.Property<string>("Result_Docnum")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("result_docnum");

                            b1.Property<string>("Valid_Date")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("valid_date");

                            b1.Property<string>("Verification_Date")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("verification_date");

                            b1.Property<string>("Vri_Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vri_id");

                            b1.HasKey("EtalonNumber", "Id")
                                .HasName("pk_etalon_verification_docs");

                            b1.ToTable("etalon_verification_docs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EtalonNumber")
                                .HasConstraintName("fk_etalon_verification_docs_etalons_etalon_number");
                        });

                    b.Navigation("CResults");
                });

            modelBuilder.Entity("Infrastructure.FGIS.Database.Entities.Verification", b =>
                {
                    b.OwnsOne("Infrastructure.FGIS.Database.Entities.Verification+InfoClass", "Info", b1 =>
                        {
                            b1.Property<string>("VerificationVri_id")
                                .HasColumnType("text")
                                .HasColumnName("vri_id");

                            b1.Property<string>("Additional_Info")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("info_additional_info");

                            b1.Property<bool>("BriefIndicator")
                                .HasColumnType("boolean")
                                .HasColumnName("info_brief_indicator");

                            b1.HasKey("VerificationVri_id");

                            b1.ToTable("verifications");

                            b1.WithOwner()
                                .HasForeignKey("VerificationVri_id")
                                .HasConstraintName("fk_verifications_verifications_vri_id");
                        });

                    b.OwnsOne("Infrastructure.FGIS.Database.Entities.Verification+MeansClass", "Means", b1 =>
                        {
                            b1.Property<string>("VerificationVri_id")
                                .HasColumnType("text")
                                .HasColumnName("vri_id");

                            b1.HasKey("VerificationVri_id");

                            b1.ToTable("verifications");

                            b1.WithOwner()
                                .HasForeignKey("VerificationVri_id")
                                .HasConstraintName("fk_verifications_verifications_vri_id");

                            b1.OwnsMany("Infrastructure.FGIS.Database.Entities.Verification+Mietum", "Mieta", b2 =>
                                {
                                    b2.Property<string>("MeansClassVerificationVri_id")
                                        .HasColumnType("text")
                                        .HasColumnName("means_class_verification_vri_id");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("ManufactureNum")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("manufacture_num");

                                    b2.Property<int>("ManufactureYear")
                                        .HasColumnType("integer")
                                        .HasColumnName("manufacture_year");

                                    b2.Property<string>("MietaURL")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mieta_url");

                                    b2.Property<string>("MitypeNumber")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mitype_number");

                                    b2.Property<string>("MitypeTitle")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mitype_title");

                                    b2.Property<string>("MitypeURL")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mitype_url");

                                    b2.Property<string>("Modification")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("modification");

                                    b2.Property<string>("Notation")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("notation");

                                    b2.Property<string>("RankCode")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("rank_code");

                                    b2.Property<string>("RankTitle")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("rank_title");

                                    b2.Property<string>("RegNumber")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("reg_number");

                                    b2.Property<string>("SchemaTitle")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("schema_title");

                                    b2.HasKey("MeansClassVerificationVri_id", "Id")
                                        .HasName("pk_mietum");

                                    b2.ToTable("mietum", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MeansClassVerificationVri_id")
                                        .HasConstraintName("fk_mietum_verifications_means_class_verification_vri_id");
                                });

                            b1.Navigation("Mieta");
                        });

                    b.OwnsOne("Infrastructure.FGIS.Database.Entities.Verification+MiInfoClass", "MiInfo", b1 =>
                        {
                            b1.Property<string>("VerificationVri_id")
                                .HasColumnType("text")
                                .HasColumnName("vri_id");

                            b1.HasKey("VerificationVri_id");

                            b1.ToTable("verifications");

                            b1.WithOwner()
                                .HasForeignKey("VerificationVri_id")
                                .HasConstraintName("fk_verifications_verifications_vri_id");

                            b1.OwnsOne("Infrastructure.FGIS.Database.Entities.Verification+SingleMI", "SingleMI", b2 =>
                                {
                                    b2.Property<string>("MiInfoClassVerificationVri_id")
                                        .HasColumnType("text")
                                        .HasColumnName("vri_id");

                                    b2.Property<string>("ManufactureNum")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mi_info_single_mi_manufacture_num");

                                    b2.Property<int>("ManufactureYear")
                                        .HasColumnType("integer")
                                        .HasColumnName("mi_info_single_mi_manufacture_year");

                                    b2.Property<string>("MitypeNumber")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mi_info_single_mi_mitype_number");

                                    b2.Property<string>("MitypeTitle")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mi_info_single_mi_mitype_title");

                                    b2.Property<string>("MitypeType")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mi_info_single_mi_mitype_type");

                                    b2.Property<string>("MitypeURL")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mi_info_single_mi_mitype_url");

                                    b2.Property<string>("Modification")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("mi_info_single_mi_modification");

                                    b2.HasKey("MiInfoClassVerificationVri_id");

                                    b2.ToTable("verifications");

                                    b2.WithOwner()
                                        .HasForeignKey("MiInfoClassVerificationVri_id")
                                        .HasConstraintName("fk_verifications_verifications_vri_id");
                                });

                            b1.Navigation("SingleMI")
                                .IsRequired();
                        });

                    b.OwnsOne("Infrastructure.FGIS.Database.Entities.Verification+VriInfoClass", "VriInfo", b1 =>
                        {
                            b1.Property<string>("VerificationVri_id")
                                .HasColumnType("text")
                                .HasColumnName("vri_id");

                            b1.Property<string>("DocTitle")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vri_info_doc_title");

                            b1.Property<string>("MiOwner")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vri_info_mi_owner");

                            b1.Property<string>("Organization")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vri_info_organization");

                            b1.Property<string>("SignCipher")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vri_info_sign_cipher");

                            b1.Property<DateOnly>("ValidDate")
                                .HasColumnType("date")
                                .HasColumnName("vri_info_valid_date");

                            b1.Property<DateOnly>("VrfDate")
                                .HasColumnType("date")
                                .HasColumnName("vri_info_vrf_date");

                            b1.Property<string>("VriType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vri_info_vri_type");

                            b1.HasKey("VerificationVri_id");

                            b1.ToTable("verifications");

                            b1.WithOwner()
                                .HasForeignKey("VerificationVri_id")
                                .HasConstraintName("fk_verifications_verifications_vri_id");

                            b1.OwnsOne("Infrastructure.FGIS.Database.Entities.Verification+Applicable", "Applicable", b2 =>
                                {
                                    b2.Property<string>("VriInfoClassVerificationVri_id")
                                        .HasColumnType("text")
                                        .HasColumnName("vri_id");

                                    b2.Property<string>("CertNum")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("vri_info_applicable_cert_num");

                                    b2.Property<bool>("SignMi")
                                        .HasColumnType("boolean")
                                        .HasColumnName("vri_info_applicable_sign_mi");

                                    b2.Property<bool>("SignPass")
                                        .HasColumnType("boolean")
                                        .HasColumnName("vri_info_applicable_sign_pass");

                                    b2.HasKey("VriInfoClassVerificationVri_id");

                                    b2.ToTable("verifications");

                                    b2.WithOwner()
                                        .HasForeignKey("VriInfoClassVerificationVri_id")
                                        .HasConstraintName("fk_verifications_verifications_vri_id");
                                });

                            b1.Navigation("Applicable")
                                .IsRequired();
                        });

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Means")
                        .IsRequired();

                    b.Navigation("MiInfo")
                        .IsRequired();

                    b.Navigation("VriInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
